### ISSUE TITLE
DailyTotal component

### ISSUE THREAD

**Issue by peasandwell** [HeathWallace/ethereum-pos#82]
Create a rolling daily total component to show the vendor the total monetary value of the transactions made on that day.

### Input props

- `value`: the monetary total of transactions made on that day

### Sub-tasks

- [x] Base component outputting the total
- [x] Container to calculate the total
- [x] Design
- [ ] Updating component to match design

**Comment by peasandwell** [comment]
Initial draft has been completed, however this still needs a formal design and hooking up to the data

**Comment by ShaunBulbrook** [comment]
Matt to look into the UX/Design

**Comment by m-potts** [comment]
An initial solution has been designed and added to the Invision prototype [https://heathwallace.invisionapp.com/share/ENFXAUAMSQY#/screens/282595069](url)

**Comment by peasandwell** [comment]
The critical intentions of this ticket has been completed, I'll close this ticket and raise a a separate ticket for the updated design.

**Comment by peasandwell** [comment]
New ticket for design implementation has been opened here: #97
